services:
  qc.fair_bumpy-yellow-hedgehog:
    command: sleep 6000000
    image: ferag/fair_eva:test
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
